
services:
  postgres:
    image: postgres:latest  # Use the latest stable PostgreSQL version
    container_name: recipe_db  # Name your container
    restart: always  # Restart automatically if the container stops
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

volumes:
  postgres_data:  # Named volume to persist database data
