version: "3.8"

services:
  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: recipe_db
    restart: always
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipe_network

  # Express.js backend (server)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: recipe_server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    networks:
      - recipe_network
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:

networks:
  recipe_network:
