version: "3.8"

services:
  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: recipe_db
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipe_network

  # Express.js backend (server)
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe_server
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on: 
      - postgres
    networks:
      - recipe_network
    command: npm start

volumes:
  postgres_data:

networks:
  recipe_network:
