name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_IP }}" > ~/.ssh/known_host_ip
          
          # Save SSH key with correct formatting using HEREDOC
          cat <<EOF > ~/.ssh/id_rsa
                ${{ secrets.SSH_PRIVATE_KEY }}
                    EOF
          chmod 600 ~/.ssh/id_rsa
          

          # Add Droplet to known_hosts
          ssh-keyscan -H "$(cat ~/.ssh/known_host_ip)" >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.DROPLET_IP }} echo "SSH connection successful"

      - name: Deploy to Droplet
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.DROPLET_IP }} << 'EOF'
            set -e
            cd ~/AI-recipe-search/server
            git reset --hard origin/master
            git pull origin master
            rm -rf ~/AI-recipe-search/client

            # Stop and remove existing containers
            docker compose down --remove-orphans || true
            docker rm -f recipe_db recipe_server || true

            # Clean up dangling images (optional)
            docker system prune -f

            # Start fresh containers
            docker compose build --no-cache
            docker compose up -d
          EOF
