name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx for cross-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4. Build and push Docker image for the server
      - name: Build and push Docker image
        run: |
          docker build -t hammad123/ai-recipe-search-backend:latest ./server
          docker push hammad123/ai-recipe-search-backend:latest

      # 5. SSH into DigitalOcean and deploy
      - name: SSH into DigitalOcean and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/AI-Recipe-Search-backend
            docker-compose down
            docker-compose pull
            docker-compose up -d
